export type TeamInfo = {
  name: string;
  flag: string;
  flagUrl?: string;
};

export const teams: Record<string, TeamInfo> = {
  Mexico: { name: "Mexique", flag: "🇲🇽" },
  Mexique: { name: "Mexique", flag: "🇲🇽" },
  "South Africa": { name: "Afrique du Sud", flag: "🇿🇦" },
  "Afrique du Sud": { name: "Afrique du Sud", flag: "🇿🇦" },
  "Korea Republic": { name: "Corée du Sud", flag: "🇰🇷" },
  "Corée du Sud": { name: "Corée du Sud", flag: "🇰🇷" },
  Czechia: { name: "Tchéquie", flag: "🇨🇿" },
  Tchéquie: { name: "Tchéquie", flag: "🇨🇿" },
  Canada: { name: "Canada", flag: "🇨🇦" },
  Switzerland: { name: "Suisse", flag: "🇨🇭" },
  Suisse: { name: "Suisse", flag: "🇨🇭" },
  Qatar: { name: "Qatar", flag: "🇶🇦" },
  "Bosnia and Herzegovina": { name: "Bosnie-Herzégovine", flag: "🇧🇦" },
  "Bosnie-Herzégovine": { name: "Bosnie-Herzégovine", flag: "🇧🇦" },
  Brazil: { name: "Brésil", flag: "🇧🇷" },
  Brésil: { name: "Brésil", flag: "🇧🇷" },
  Morocco: { name: "Maroc", flag: "🇲🇦" },
  Maroc: { name: "Maroc", flag: "🇲🇦" },
  Haiti: { name: "Haïti", flag: "🇭🇹" },
  Haïti: { name: "Haïti", flag: "🇭🇹" },
  Scotland: { name: "Écosse", flag: "SCO", flagUrl: "https://flagcdn.com/gb-sct.svg" },
  Écosse: { name: "Écosse", flag: "SCO", flagUrl: "https://flagcdn.com/gb-sct.svg" },
  "United States": { name: "États-Unis", flag: "🇺🇸" },
  "États-Unis": { name: "États-Unis", flag: "🇺🇸" },
  Paraguay: { name: "Paraguay", flag: "🇵🇾" },
  Australia: { name: "Australie", flag: "🇦🇺" },
  Australie: { name: "Australie", flag: "🇦🇺" },
  Turkiye: { name: "Turquie", flag: "🇹🇷" },
  Turquie: { name: "Turquie", flag: "🇹🇷" },
  Germany: { name: "Allemagne", flag: "🇩🇪" },
  Allemagne: { name: "Allemagne", flag: "🇩🇪" },
  Curacao: { name: "Curaçao", flag: "🇨🇼" },
  Curaçao: { name: "Curaçao", flag: "🇨🇼" },
  "Ivory Coast": { name: "Côte d’Ivoire", flag: "🇨🇮" },
  "Côte d’Ivoire": { name: "Côte d’Ivoire", flag: "🇨🇮" },
  Ecuador: { name: "Équateur", flag: "🇪🇨" },
  Équateur: { name: "Équateur", flag: "🇪🇨" },
  Netherlands: { name: "Pays-Bas", flag: "🇳🇱" },
  "Pays-Bas": { name: "Pays-Bas", flag: "🇳🇱" },
  Japan: { name: "Japon", flag: "🇯🇵" },
  Japon: { name: "Japon", flag: "🇯🇵" },
  Tunisia: { name: "Tunisie", flag: "🇹🇳" },
  Tunisie: { name: "Tunisie", flag: "🇹🇳" },
  Sweden: { name: "Suède", flag: "🇸🇪" },
  Suède: { name: "Suède", flag: "🇸🇪" },
  Belgium: { name: "Belgique", flag: "🇧🇪" },
  Belgique: { name: "Belgique", flag: "🇧🇪" },
  Egypt: { name: "Égypte", flag: "🇪🇬" },
  Égypte: { name: "Égypte", flag: "🇪🇬" },
  Iran: { name: "Iran", flag: "🇮🇷" },
  "New Zealand": { name: "Nouvelle-Zélande", flag: "🇳🇿" },
  "Nouvelle-Zélande": { name: "Nouvelle-Zélande", flag: "🇳🇿" },
  Spain: { name: "Espagne", flag: "🇪🇸" },
  Espagne: { name: "Espagne", flag: "🇪🇸" },
  "Cape Verde": { name: "Cap-Vert", flag: "🇨🇻" },
  "Cap-Vert": { name: "Cap-Vert", flag: "🇨🇻" },
  "Saudi Arabia": { name: "Arabie saoudite", flag: "🇸🇦" },
  "Arabie saoudite": { name: "Arabie saoudite", flag: "🇸🇦" },
  Uruguay: { name: "Uruguay", flag: "🇺🇾" },
  France: { name: "France", flag: "🇫🇷" },
  Senegal: { name: "Sénégal", flag: "🇸🇳" },
  Sénégal: { name: "Sénégal", flag: "🇸🇳" },
  Norway: { name: "Norvège", flag: "🇳🇴" },
  Norvège: { name: "Norvège", flag: "🇳🇴" },
  Iraq: { name: "Irak", flag: "🇮🇶" },
  Irak: { name: "Irak", flag: "🇮🇶" },
  Argentina: { name: "Argentine", flag: "🇦🇷" },
  Argentine: { name: "Argentine", flag: "🇦🇷" },
  Algeria: { name: "Algérie", flag: "🇩🇿" },
  Algérie: { name: "Algérie", flag: "🇩🇿" },
  Austria: { name: "Autriche", flag: "🇦🇹" },
  Autriche: { name: "Autriche", flag: "🇦🇹" },
  Jordan: { name: "Jordanie", flag: "🇯🇴" },
  Jordanie: { name: "Jordanie", flag: "🇯🇴" },
  Portugal: { name: "Portugal", flag: "🇵🇹" },
  Uzbekistan: { name: "Ouzbékistan", flag: "🇺🇿" },
  Ouzbékistan: { name: "Ouzbékistan", flag: "🇺🇿" },
  Colombia: { name: "Colombie", flag: "🇨🇴" },
  Colombie: { name: "Colombie", flag: "🇨🇴" },
  "DR Congo": { name: "RD Congo", flag: "🇨🇩" },
  "RD Congo": { name: "RD Congo", flag: "🇨🇩" },
  England: { name: "Angleterre", flag: "ENG", flagUrl: "https://flagcdn.com/gb-eng.svg" },
  Angleterre: { name: "Angleterre", flag: "ENG", flagUrl: "https://flagcdn.com/gb-eng.svg" },
  Croatia: { name: "Croatie", flag: "🇭🇷" },
  Croatie: { name: "Croatie", flag: "🇭🇷" },
  Ghana: { name: "Ghana", flag: "🇬🇭" },
  Panama: { name: "Panama", flag: "🇵🇦" }
};

export function teamInfo(team: string) {
  return teams[team] ?? { name: team, flag: "🏳️" };
}

export function teamName(team: string) {
  return teamInfo(team).name;
}
